### ISSUE TITLE
Can I decompile the whole executable / library file to LLVM IR?

### ISSUE THREAD

**Issue by Kelvin-Ng** [draperlaboratory/fracture#56]
I know how to decompile a function of an executable or library file of a specific address. Does this project include a function to (statically analysis the executable or library file and) decompile the whole file to LLVM IR, so that I can compile the LLVM IR to form an executable or library file again?

What I actually want to do is to do static binary translation from ARM to x86. So, if you have any alternative methods, please let me know. Thanks.

**Comment by rtc-draper** [comment]
As stated in the docs, Fracture is designed for analysis not binary rewriting and/or re-targeting. It would provide a good starting point to build such a tool. It might also be possible to get it to work for very limited toy cases right now, but to go any further would be a project.
