### ISSUE TITLE
How does one pure assembly instruction transform to llvm-ir?

### ISSUE THREAD

**Issue by chlizheng** [draperlaboratory/fracture#60]
Hi.
Now I want to transform pure stm8 assembly instructions to llvm-ir. Is that feasible? And Can I just learn the instruction reference section of llvm-ir to do this job?
best regards.

**Comment by pgoodman** [comment]
@chlizheng you should check out [Remill](https://github.com/trailofbits/remill). It doesn't support the STM8 architecture, though you could add it. Then you can use [remill-lift](https://github.com/trailofbits/remill/tree/master/tools/lift#remill-lift-) to see what the LLVM IR associated with instructions looks like.
